# VHDL language server config

# Use VHDL'08
standard = "2008"

[libraries]

# Regular files
lib.files = [
  'src/**/hdl/*.vhd',
  'lib/**/src/**/hdl/*.vhd',
  'build/regs_out/**/hdl/*.vhd',
  'test/**/*.vhd',
]

# Vunit library files
vunit_lib.files = [
  '$VUNIT_ROOTDIR/vhdl/*.vhd',
  '$VUNIT_ROOTDIR/vhdl/check/src/*.vhd',
  '$VUNIT_ROOTDIR/vhdl/com/src/*.vhd',
  '$VUNIT_ROOTDIR/vhdl/core/src/core_pkg.vhd',
  '$VUNIT_ROOTDIR/vhdl/core/src/stop_body_2008p.vhd',
  '$VUNIT_ROOTDIR/vhdl/core/src/stop_pkg.vhd', 
  '$VUNIT_ROOTDIR/vhdl/data_types/src/byte_vector_ptr_pkg.vhd',
  '$VUNIT_ROOTDIR/vhdl/data_types/src/codec-2008p.vhd',
  '$VUNIT_ROOTDIR/vhdl/data_types/src/codec_builder-2008p.vhd',
  '$VUNIT_ROOTDIR/vhdl/data_types/src/codec_builder.vhd',
  '$VUNIT_ROOTDIR/vhdl/data_types/src/codec.vhd',
  '$VUNIT_ROOTDIR/vhdl/data_types/src/data_types_context.vhd',
  '$VUNIT_ROOTDIR/vhdl/data_types/src/data_types_private_pkg.vhd',
  '$VUNIT_ROOTDIR/vhdl/data_types/src/dict_pkg-2008p.vhd',
  '$VUNIT_ROOTDIR/vhdl/data_types/src/dict_pkg-body.vhd',
  '$VUNIT_ROOTDIR/vhdl/data_types/src/dict_pkg.vhd',
  '$VUNIT_ROOTDIR/vhdl/data_types/src/event_common_pkg.vhd',
  '$VUNIT_ROOTDIR/vhdl/data_types/src/event_pkg.vhd',
  '$VUNIT_ROOTDIR/vhdl/data_types/src/event_private_pkg.vhd',
  '$VUNIT_ROOTDIR/vhdl/data_types/src/id_pkg.vhd',
  '$VUNIT_ROOTDIR/vhdl/data_types/src/integer_array_pkg-body.vhd',
  '$VUNIT_ROOTDIR/vhdl/data_types/src/integer_array_pkg.vhd',
  '$VUNIT_ROOTDIR/vhdl/data_types/src/integer_vector_ptr_pkg-body-2002p.vhd',
  '$VUNIT_ROOTDIR/vhdl/data_types/src/integer_vector_ptr_pkg.vhd',
  '$VUNIT_ROOTDIR/vhdl/data_types/src/integer_vector_ptr_pool_pkg.vhd',
  '$VUNIT_ROOTDIR/vhdl/data_types/src/queue_pkg-2008p.vhd',
  '$VUNIT_ROOTDIR/vhdl/data_types/src/queue_pkg-body.vhd',
  '$VUNIT_ROOTDIR/vhdl/data_types/src/queue_pkg.vhd',
  '$VUNIT_ROOTDIR/vhdl/data_types/src/queue_pool_pkg.vhd',
  '$VUNIT_ROOTDIR/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd',
  '$VUNIT_ROOTDIR/vhdl/data_types/src/string_ptr_pkg.vhd',
  '$VUNIT_ROOTDIR/vhdl/data_types/src/string_ptr_pool_pkg.vhd',
  '$VUNIT_ROOTDIR/vhdl/data_types/src/types.vhd',
  '$VUNIT_ROOTDIR/vhdl/data_types/src/api/*.vhd',
  '$VUNIT_ROOTDIR/vhdl/dictionary/src/*.vhd',
  '$VUNIT_ROOTDIR/vhdl/logging/src/ansi_pkg.vhd',
  '$VUNIT_ROOTDIR/vhdl/logging/src/common_log_pkg-body.vhd',
  '$VUNIT_ROOTDIR/vhdl/logging/src/common_log_pkg.vhd',
  '$VUNIT_ROOTDIR/vhdl/logging/src/file_pkg.vhd',
  '$VUNIT_ROOTDIR/vhdl/logging/src/location_pkg-body-2008m.vhd',
  '$VUNIT_ROOTDIR/vhdl/logging/src/location_pkg.vhd',
  '$VUNIT_ROOTDIR/vhdl/logging/src/logger_pkg-body.vhd',
  '$VUNIT_ROOTDIR/vhdl/logging/src/logger_pkg.vhd',
  '$VUNIT_ROOTDIR/vhdl/logging/src/log_handler_pkg-body.vhd',
  '$VUNIT_ROOTDIR/vhdl/logging/src/log_handler_pkg.vhd',
  '$VUNIT_ROOTDIR/vhdl/logging/src/log_levels_pkg-body.vhd',
  '$VUNIT_ROOTDIR/vhdl/logging/src/log_levels_pkg.vhd',
  '$VUNIT_ROOTDIR/vhdl/logging/src/print_pkg-body.vhd',
  '$VUNIT_ROOTDIR/vhdl/logging/src/print_pkg.vhd',
  '$VUNIT_ROOTDIR/vhdl/path/src/*.vhd',
  '$VUNIT_ROOTDIR/vhdl/random/src/*.vhd',
  '$VUNIT_ROOTDIR/vhdl/run/src/*.vhd',
  '$VUNIT_ROOTDIR/vhdl/string_ops/src/*.vhd',
  '$VUNIT_ROOTDIR/vhdl/verification_components/src/*.vhd',
]
vunit_lib.is_third_party = true

# OSVVM library files
osvvm.files = [
  '$VUNIT_ROOTDIR/vhdl/osvvm/*.vhd',
]
osvvm.is_third_party = true

JSON.files = [
  '$VUNIT_ROOTDIR/vhdl/JSON-for-VHDL/src/*.vhdl',
]
JSON.is_third_party = true

[lint]
unnecessary_work_library = false # Disable linting for the 'library work;' statement
