################################################################################
# File : adder.toml
# Auth : David Gussler
# Lang : HDL-Registers TOML
#        https://hdl-registers.com/rst/user_guide/getting_started.html
# ==============================================================================
# Shrikebyte FPGA Template - https://github.com/shrikebyte/template_fpga
# Copyright (C) Shrikebyte, LLC
# Licensed under the Apache 2.0 license, see LICENSE for details.
# ==============================================================================
# Registers for the adder example
################################################################################


################################################################################
[a]
description = "Operand A."
mode = "r_w"

data.type = "bit_vector"
data.width = 32
data.description = """
Operand A.
"""


################################################################################
[b]
description = "Operand B."
mode = "r_w"

data.type = "bit_vector"
data.width = 32
data.description = """
Operand B.
"""


################################################################################
[c]
description = "Result C."
mode = "r"

data.type = "bit_vector"
data.width = 32
data.description = """
Result C.
"""
